// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: logs.proto

package logs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LogSerivce_WriteLog_FullMethodName = "/logs.LogSerivce/WriteLog"
)

// LogSerivceClient is the client API for LogSerivce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogSerivceClient interface {
	WriteLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
}

type logSerivceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogSerivceClient(cc grpc.ClientConnInterface) LogSerivceClient {
	return &logSerivceClient{cc}
}

func (c *logSerivceClient) WriteLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, LogSerivce_WriteLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogSerivceServer is the server API for LogSerivce service.
// All implementations must embed UnimplementedLogSerivceServer
// for forward compatibility
type LogSerivceServer interface {
	WriteLog(context.Context, *LogRequest) (*LogResponse, error)
	mustEmbedUnimplementedLogSerivceServer()
}

// UnimplementedLogSerivceServer must be embedded to have forward compatible implementations.
type UnimplementedLogSerivceServer struct {
}

func (UnimplementedLogSerivceServer) WriteLog(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteLog not implemented")
}
func (UnimplementedLogSerivceServer) mustEmbedUnimplementedLogSerivceServer() {}

// UnsafeLogSerivceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogSerivceServer will
// result in compilation errors.
type UnsafeLogSerivceServer interface {
	mustEmbedUnimplementedLogSerivceServer()
}

func RegisterLogSerivceServer(s grpc.ServiceRegistrar, srv LogSerivceServer) {
	s.RegisterService(&LogSerivce_ServiceDesc, srv)
}

func _LogSerivce_WriteLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogSerivceServer).WriteLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogSerivce_WriteLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogSerivceServer).WriteLog(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogSerivce_ServiceDesc is the grpc.ServiceDesc for LogSerivce service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogSerivce_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logs.LogSerivce",
	HandlerType: (*LogSerivceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteLog",
			Handler:    _LogSerivce_WriteLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logs.proto",
}
